# Stage 1: Build
FROM node:20-slim AS build

ARG EXPO_PUBLIC_API_BASE_URL
ENV EXPO_PUBLIC_API_BASE_URL=$EXPO_PUBLIC_API_BASE_URL

WORKDIR /app

# Abhängigkeiten kopieren
COPY package*.json ./

# Installiere Abhängigkeiten
RUN npm install

# Restlichen Code kopieren
COPY . .

# Web-Build erstellen
RUN npm run build

# Stage 2: Serve
FROM nginx:stable-alpine

# Kopiere gebaute Dateien aus Stage 1
COPY --from=build /app/web-build /usr/share/nginx/html

# Port 80 exponieren
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
