name: 'Setup Mobile'
description: 'Setzt Node ein und installiert Mobile-Abhängigkeiten'
runs:
  using: "composite"
  steps:
    - name: 📱 Node 20 einrichten
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        cache-dependency-path: 'mobile/package-lock.json'

    - name: 📦 Mobile-Abhängigkeiten
      shell: bash
      run: |
        bash tools/dev/pipeline/ci_steps.sh mobile_install_deps
